version: '3'
services:
  database:
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - "5432:5432"
    volumes:
      - "./.data/docker-data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=graphql_api
      - POSTGRES_USER=graphql_api
      - POSTGRES_PASSWORD=graphql_api
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
